### ISSUE TITLE
Additional options for how non-rigid tracking is done

### ISSUE THREAD

**Issue by Algomorph** [Algomorph/InfiniTAM#183]
- [x] Simplify declaration & definition of serializable structs with variadic macro meta-programming
- [x] SImplify declaration & definition of serializabel enums with variadic macro meta-programming
- [x] Option to switch expanded allocation on or off
- [x] Option to change the rear block allocation bound
- [x] Add verbosity_level enum & setting in Config
