### ISSUE TITLE
Re-implement the "Extended" Tracker using the new traversal techniques & lambdas.

### ISSUE THREAD

**Issue by Algomorph** [Algomorph/InfiniTAM#309]
The new tracker will stick to the "Engine" convention for now. We can tentatively call it DenseColorAndDepthRigidAlignmentEngine, but it might make sense to combine the different tracker variants in a single class in case the old "Extended" tracker actually re-uses large portions of code from the old "Depth" tracker and the old "Color" tracker.

- [ ] Inspect whether and which portions of code are reused by Extended tracker from Depth Tracker and Color Tracker
- [ ] Inspect what kind of hierarchies do all three store and whether they can be combined

At this point, we should be more or less clear on what the architecture should be (how to organize the data and the classes/structs). 

Stick to the old function interface for now, hence the following functions will need to be re-implemented and tested for CPU/GPU and PVA/VBH:
- [ ] Constructor and supporting methods, destructor (the first BIG one)
- [ ] CanKeepTracking
- [ ] TrackCamera (the second BIG one)
- [ ] Update Initial Pose
- [ ] RequiresColourRendering
- [ ] RequiresDepthReliability
- [ ] RequiresPointCloudRendering
